-- Create Chat Messages Table
create table if not exists public."Chat_Messages" (
    id bigint generated by default as identity primary key,
    sender_id text not null,
    -- 'admin' or driver_id
    receiver_id text not null,
    -- 'admin' or driver_id
    message text not null,
    is_read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Enable Realtime
alter publication supabase_realtime
add table public."Chat_Messages";
-- Policies (Simple for now: authenticated users can read/insert their own messages)
alter table public."Chat_Messages" enable row level security;
create policy "Users can read their own messages" on public."Chat_Messages" for
select to authenticated using (
        auth.uid()::text = sender_id
        or auth.uid()::text = receiver_id
        or sender_id = 'admin'
        or receiver_id = 'admin' -- Simplification: In real app, check role
    );
create policy "Users can insert their own messages" on public."Chat_Messages" for
insert to authenticated with check (auth.uid()::text = sender_id);