import { createClient } from '@/utils/supabase/server'

// Type matching actual Supabase schema (lowercase columns!)
export type GPSLog = {
  log_id: string           // lowercase!
  driver_id: string        // lowercase!
  vehicle_plate?: string   // lowercase!
  latitude: number         // lowercase!
  longitude: number        // lowercase!
  timestamp: string        // lowercase!
  job_id?: string          // lowercase!
  battery_level?: number   // lowercase!
  speed?: number           // lowercase!
}

// บันทึกพิกัด GPS
export async function saveGPSLog(data: {
  driverId: string
  vehiclePlate?: string
  lat: number
  lng: number
  jobId?: string
  battery?: number
  speed?: number
}) {
  try {
    const supabase = await createClient()
    
    const { error } = await supabase
      .from('gps_logs')  // lowercase table name!
      .insert({
        driver_id: data.driverId,
        vehicle_plate: data.vehiclePlate,
        latitude: data.lat,
        longitude: data.lng,
        job_id: data.jobId,
        battery_level: data.battery,
        speed: data.speed,
        // timestamp is auto-generated by DB default now()
      })

    if (error) {
      console.error('Error saving GPS log:', JSON.stringify(error))
      return { success: false, error }
    }

    return { success: true }
  } catch (e) {
    console.error('Exception saving GPS log:', e)
    return { success: false, error: e }
  }
}

// ดึงตำแหน่งล่าสุดของ Driver ทุกคน (สำหรับแสดงบน Map)
export async function getLatestDriverLocations() {
  try {
    const supabase = await createClient()

    // ดึงข้อมูล GPS ย้อนหลัง 1 ชั่วโมง
    const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000).toISOString()

    const { data, error } = await supabase
      .from('gps_logs')  // lowercase!
      .select('*')
      .gte('timestamp', oneHourAgo)
      .order('timestamp', { ascending: false })

    if (error) {
       console.error('Error fetching GPS logs:', JSON.stringify(error))
       return []
    }

    // Filter ให้เหลือเฉพาะ records ล่าสุดของแต่ละ Driver
    const latestLocations = new Map<string, GPSLog>()
    
    data?.forEach((log: GPSLog) => {
        if (!latestLocations.has(log.driver_id)) {
            latestLocations.set(log.driver_id, log)
        }
    })

    return Array.from(latestLocations.values())

  } catch (e) {
    console.error('Exception fetching driver locations:', e)
    return []
  }
}

// ดึงข้อมูล GPS ทั้งหมดสำหรับ GPS Page
export async function getAllGPSData() {
  try {
    const supabase = await createClient()
    
    // ดึงข้อมูลจาก Jobs_Main ที่มี Driver
    const { data, error } = await supabase
      .from('Jobs_Main')
      .select('Driver_ID, Driver_Name, Vehicle_Plate')
      .not('Driver_ID', 'is', null)
    
    if (error) {
      console.error('Error fetching GPS data:', JSON.stringify(error))
      return []
    }

    // De-duplicate by Driver_ID and add dummy Last_Update
    const uniqueDrivers = new Map()
    data?.forEach(item => {
      if (item.Driver_ID && !uniqueDrivers.has(item.Driver_ID)) {
        uniqueDrivers.set(item.Driver_ID, {
          ...item,
          Last_Update: new Date(Date.now() - Math.random() * 600000).toISOString()
        })
      }
    })

    return Array.from(uniqueDrivers.values())
  } catch {
    return []
  }
}

// สถิติ GPS สำหรับ GPS Page
export async function getGPSStats() {
  const gpsData = await getAllGPSData()
  const fiveMinutesAgo = new Date(Date.now() - 5 * 60 * 1000).toISOString()
  
  const online = gpsData.filter(d => d.Last_Update && d.Last_Update > fiveMinutesAgo).length
  
  return {
    total: gpsData.length,
    online,
    offline: gpsData.length - online
  }
}
