"use server"

import { createClient } from '@/utils/supabase/server'

// Type matching actual Supabase schema (ProperCase columns!)
export type GPSLog = {
  Log_ID: string
  Driver_ID: string
  Vehicle_Plate?: string
  Latitude: number
  Longitude: number
  Timestamp: string
  Job_ID?: string
  Battery_Level?: number
  Speed?: number
}

// บันทึกพิกัด GPS
export async function saveGPSLog(data: {
  driverId: string
  vehiclePlate?: string
  lat: number
  lng: number
  jobId?: string
  battery?: number
  speed?: number
}) {
  try {
    const supabase = await createClient()
    
    const { error } = await supabase
      .from('GPS_Logs')
      .insert({
        Driver_ID: data.driverId,
        Vehicle_Plate: data.vehiclePlate,
        Latitude: data.lat,
        Longitude: data.lng,
        Job_ID: data.jobId,
        Battery_Level: data.battery,
        Speed: data.speed,
        // Timestamp is auto-generated by DB default now()
      })

    if (error) {
      console.error('Error saving GPS log:', JSON.stringify(error))
      return { success: false, error }
    }

    return { success: true }
  } catch (e) {
    console.error('Exception saving GPS log:', e)
    return { success: false, error: e }
  }
}

// ดึงตำแหน่งล่าสุดของ Driver ทุกคน (สำหรับแสดงบน Map)
export async function getLatestDriverLocations() {
  try {
    const supabase = await createClient()

    // ดึงข้อมูล GPS ย้อนหลัง 1 ชั่วโมง
    const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000).toISOString()

    const { data, error } = await supabase
      .from('GPS_Logs')
      .select(`
        *,
        Master_Drivers ( Driver_Name )
      `)
      .gte('Timestamp', oneHourAgo)
      .order('Timestamp', { ascending: false })

    if (error) {
       console.error('Error fetching GPS logs:', JSON.stringify(error))
       return []
    }

    // Filter ให้เหลือเฉพาะ records ล่าสุดของแต่ละ Driver
    const latestLocations = new Map<string, any>()
    
    data?.forEach((log) => {
        if (!latestLocations.has(log.Driver_ID)) {
            latestLocations.set(log.Driver_ID, {
              ...log,
              Driver_Name: log.Master_Drivers?.Driver_Name || 'Unknown Driver'
            })
        }
    })

    return Array.from(latestLocations.values())

  } catch (e) {
    console.error('Exception fetching driver locations:', e)
    return []
  }
}

// ดึงประวัติการเดินทางของ Driver ตามวันที่ (สำหรับแสดงเส้นทาง)
export async function getDriverRouteForDate(driverId: string, date: string) {
  try {
    const supabase = await createClient()

    // Create Start and End timestamps for the day
    const startDate = `${date}T00:00:00`
    const endDate = `${date}T23:59:59`

    const { data, error } = await supabase
      .from('GPS_Logs')
      .select('Latitude, Longitude, Timestamp')
      .eq('Driver_ID', driverId)
      .gte('Timestamp', startDate)
      .lte('Timestamp', endDate)
      .order('Timestamp', { ascending: true })

    if (error) {
      console.error('Error fetching driver route:', JSON.stringify(error))
      return []
    }

    return data || []
  } catch (e) {
    console.error('Exception fetching driver route:', e)
    return []
  }
}
